---
abstract: 'display a menu of choices'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tickit-Widget-Menu
provides:
  Tickit::Widget::Menu:
    file: lib/Tickit/Widget/Menu.pm
    version: '0.09'
  Tickit::Widget::Menu::Item:
    file: lib/Tickit/Widget/Menu/Item.pm
    version: '0.09'
  Tickit::Widget::Menu::base:
    file: lib/Tickit/Widget/Menu/base.pm
    version: '0.09'
  Tickit::Widget::Menu::itembase:
    file: lib/Tickit/Widget/Menu/itembase.pm
    version: '0.09'
  Tickit::Widget::MenuBar:
    file: lib/Tickit/Widget/MenuBar.pm
    version: '0.09'
requires:
  Tickit::RenderBuffer: '0.43'
  Tickit::Test: '0'
  Tickit::Widget: '0.36'
  Tickit::Window: '0.43'
  perl: '5.010'
resources:
  IRC: irc://irc.freenode.net/#tickit
  license: http://dev.perl.org/licenses/
version: '0.09'
